name: swardenapp
description: "Gestor de contrasenyes open source amb Flutter"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.0.1
  encrypt: ^5.0.3
  pointycastle: ^3.9.1
  
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3

  go_router: ^16.2.4
  slang: ^4.8.1
  slang_flutter: ^4.8.0
  package_info_plus: ^9.0.0
  freezed_annotation: ^3.1.0
  url_launcher: ^6.3.2
  build_runner: ^2.7.1
  freezed: ^3.2.3
  flutter_launcher_icons: ^0.14.4
  mocktail: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_launcher_icons:
  ios: true
  remove_alpha_ios: true
  image_path: "assets/img/icon.png"


flutter:

  uses-material-design: true

  assets:
    - assets/img/
